# Generated by Django 5.0.4 on 2024-05-20 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_cuenta_delete_direccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='usuario',
            new_name='persona',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
