# Generated by Django 5.0.4 on 2024-05-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_alerones_categoria_alter_intakes_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aleron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('llant', 'Llant'), ('aleron', 'Aleron'), ('spoiler', 'Spoiler'), ('intake', 'Intake'), ('widebody', 'Widebody')], default='llanta', max_length=30)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('llant', 'Llant'), ('aleron', 'Aleron'), ('spoiler', 'Spoiler'), ('intake', 'Intake'), ('widebody', 'Widebody')], default='llanta', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Llanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('llant', 'Llant'), ('aleron', 'Aleron'), ('spoiler', 'Spoiler'), ('intake', 'Intake'), ('widebody', 'Widebody')], default='llanta', max_length=30)),
                ('diametro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medida_centro', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spoiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('llant', 'Llant'), ('aleron', 'Aleron'), ('spoiler', 'Spoiler'), ('intake', 'Intake'), ('widebody', 'Widebody')], default='llanta', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Alerones',
        ),
        migrations.DeleteModel(
            name='Intakes',
        ),
        migrations.DeleteModel(
            name='Llantas',
        ),
        migrations.DeleteModel(
            name='Spoilers',
        ),
        migrations.AlterField(
            model_name='widebody',
            name='categoria',
            field=models.CharField(choices=[('llant', 'Llant'), ('aleron', 'Aleron'), ('spoiler', 'Spoiler'), ('intake', 'Intake'), ('widebody', 'Widebody')], default='llanta', max_length=30),
        ),
    ]
