# Generated by Django 5.0.4 on 2024-05-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_aleron_categoria_alter_intake_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aleron',
            name='descripcion',
            field=models.TextField(default='Descripcion del producto'),
        ),
        migrations.AddField(
            model_name='intake',
            name='descripcion',
            field=models.TextField(default='Descripcion del producto'),
        ),
        migrations.AddField(
            model_name='llanta',
            name='descripcion',
            field=models.TextField(default='Descripcion del producto'),
        ),
        migrations.AddField(
            model_name='spoiler',
            name='descripcion',
            field=models.TextField(default='Descripcion del producto'),
        ),
        migrations.AddField(
            model_name='widebody',
            name='descripcion',
            field=models.TextField(default='Descripcion del producto'),
        ),
    ]
