# Generated by Django 5.0.4 on 2024-05-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_aleron_descripcion_intake_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aleron',
            name='altura',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='aleron',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intake',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spoiler',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='widebody',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
