# Generated by Django 5.0.4 on 2024-05-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_aleron_altura_alter_aleron_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='diametro',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
