# Generated by Django 5.0.4 on 2024-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_llanta_diametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='aleron',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='intake',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='llanta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='spoiler',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='widebody',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
