# Generated by Django 5.0.4 on 2024-05-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_aleron_imagen_intake_imagen_llanta_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aleron',
            options={'permissions': [('can_create_aleron', 'Can create Aleron'), ('can_update_aleron', 'Can update Aleron'), ('can_delete_aleron', 'Can delete Aleron')]},
        ),
        migrations.AlterModelOptions(
            name='intake',
            options={'permissions': [('can_create_intake', 'Can create Intake'), ('can_update_intake', 'Can update Intake'), ('can_delete_intake', 'Can delete Intake')]},
        ),
        migrations.AlterModelOptions(
            name='llanta',
            options={'permissions': [('can_create_llanta', 'Can create Llanta'), ('can_update_llanta', 'Can update Llanta'), ('can_delete_llanta', 'Can delete Llanta')]},
        ),
        migrations.AlterModelOptions(
            name='spoiler',
            options={'permissions': [('can_create_spoiler', 'Can create Spoiler'), ('can_update_spoiler', 'Can update Spoiler'), ('can_delete_spoiler', 'Can delete Spoiler')]},
        ),
        migrations.AlterModelOptions(
            name='widebody',
            options={'permissions': [('can_create_widebody', 'Can create Widebody'), ('can_update_widebody', 'Can update Widebody'), ('can_delete_widebody', 'Can delete Widebody')]},
        ),
    ]
